name: JustFly
main: astrxicz\JustFly\Main
author: Astrxicz
api: [3.0.0, 4.0.0]
version: 1.0.0
load: POSTWORLD

permissions:
    justfly:
        justfly.fly:
            description: "Allows you to do /fly for yourself."
            default: op
        justfy.fly_others:
            description: "Allows you to enable/disable another person's flight with /fly [player]"
            default: op