name: JustFly
main: astrxicz\JustFly\Main
author: Astrxicz
api: [3.0.0, 4.0.0]
version: 1.0.0
load: POSTWORLD

commands:
	fly:
		description: "Just fly!"
		permission: justfly.fly

permissions:
	justfly.fly:
		description: "Allows you to do /fly for yourself."
		default: true
	justfy.fly.others.enableFly:
		description: "Allows you to enable another person's flight with /fly [player]"
		default: true
	justfy.fly.others.disableFly:
		description: "Allows you to disable another person's flight with /fly [player]"
		default: true